export const TOKENS = {
  AUTH_TOKENS_REPOSITORY: "module:AUTH_TOKENS_REPOSITORY",
  AUTH_REPOSITORY: "module:AUTH_REPOSITORY",
  AUTH_STORE: "module:AUTH_STORE",
  AUTH_SERVICE: "module:AUTH_SERVICE",
  AUTH_API_CLIENT: "module:AUTH_API_CLIENT",
};
